[[ch11]]
== 比特幣安全性

保護您的比特幣具有挑戰性，因為比特幣不像銀行帳戶中的餘額。您的比特幣非常類似於數位現金或黃金。您可能聽過這句話：「佔有是法律的十分之九。」在比特幣中，佔有是法律的十分之十。擁有花費某些比特幣的金鑰相當於擁有現金或一塊貴金屬。您可能會遺失它、放錯地方、被盜竊，或不小心給某人錯誤的金額。在每一種情況下，用戶在協議內都沒有追索權，就像他們在公共人行道上掉了現金一樣。

然而，比特幣系統具有現金、黃金和銀行帳戶所沒有的能力。包含您金鑰的比特幣錢包可以像任何檔案一樣備份。它可以儲存在多個副本中，甚至可以列印在紙上作為硬拷貝備份。您無法「備份」現金、黃金或銀行帳戶。比特幣與之前出現的任何事物都有足夠的不同，以至於我們也需要以一種新穎的方式思考如何保護我們的比特幣。

=== 安全原則

比特幣中的 ((("Bitcoin", "security", "principles of", id="bitcoin-security-principle")))((("security", "principles of", id="security-principle")))((("decentralized consensus", "as security principle", secondary-sortas="security principle", id="decentral-consensus-principle")))核心原則是去中心化，它對安全性有重要影響。集中式模型，例如傳統銀行或支付網路，依賴於存取控制和審查以將不良行為者拒之門外。相比之下，像比特幣這樣的去中心化系統將責任和控制權推給用戶。因為網路的安全性基於獨立驗證，所以網路可以是開放的，比特幣流量不需要加密（儘管加密仍然可能有用）。

在傳統支付網路上，例如信用卡系統，付款是開放式的，因為它包含用戶的私人識別符（信用卡號）。在初始收費後，任何能夠存取該識別符的人都可以「拉取」資金並一次又一次地向所有者收費。因此，支付網路必須使用加密進行端到端保護，並且必須確保沒有竊聽者或中介可以在傳輸或儲存（靜態）時破壞支付流量。如果不良行為者獲得系統存取權，他可以破壞當前交易_以及_可用於創建新交易的支付憑證。更糟糕的是，當客戶資料被破壞時，客戶會面臨身份盜竊的風險，必須採取行動防止被破壞帳戶的欺詐使用。

比特幣有著顯著的不同。比特幣交易僅授權將特定價值給予特定接收者，並且無法偽造。它不會揭示任何私人資訊，例如當事人的身份，也不能用於授權額外的付款。因此，比特幣支付網路不需要加密或防止竊聽。事實上，您可以透過開放的公共頻道廣播比特幣交易，例如不安全的 WiFi 或藍牙，而不會損失安全性。

比特幣的去中心化安全模型將大量權力交到用戶手中。擁有這種權力的同時也伴隨著維護金鑰保密性的責任。對於大多數用戶來說，這並不容易做到，尤其是在通用計算設備上，例如連接網際網路的智慧型手機或筆記型電腦。儘管比特幣的去中心化模型防止了信用卡常見的大規模妥協類型，但許多用戶無法充分保護他們的金鑰，並一個接一個地被駭客入侵。

==== 安全地開發比特幣系統

比特幣開發人員的關鍵原則是去中心化。大多數開發人員將熟悉集中式安全模型，可能會想將這些模型應用於他們的比特幣應用程式，結果可能是災難性的。

比特幣的安全性依賴於對金鑰的去中心化控制和用戶的獨立交易驗證。如果您想利用比特幣的安全性，您需要確保您保持在比特幣安全模型內。簡單來說：不要從用戶手中奪走對金鑰的控制，也不要將驗證外包。

例如，許多早期的比特幣交易所將所有用戶資金集中在一個「熱」錢包中，金鑰儲存在單一伺服器上。這樣的設計從用戶手中奪走控制權，並將對金鑰的控制集中在單一系統中。許多這樣的系統已經被駭客入侵，給他們的客戶帶來災難性後果。

除非您準備大量投資於運營安全性、多層存取控制和稽核（就像傳統銀行那樣），否則您應該非常謹慎地考慮將資金帶出比特幣的去中心化安全環境。即使您有資金和紀律來實施強大的安全模型，這樣的設計僅僅複製了傳統金融網路的脆弱模型，該模型飽受身份盜竊、貪污和挪用公款的困擾。要利用比特幣獨特的去中心化安全模型，您必須避免可能感覺熟悉但最終會破壞比特幣 ((("decentralized consensus", "as security principle", secondary-sortas="security principle", startref="decentral-consensus-principle")))安全性的集中式架構的誘惑。

==== 信任根

傳統 ((("root of trust", id="root-trust")))安全架構基於一個稱為_信任根_的概念，它是一個受信任的核心，用作整個系統或應用程式安全性的基礎。安全架構圍繞信任根發展為一系列同心圓，就像洋蔥的層次一樣，從中心向外擴展信任。每一層都使用存取控制、數位簽章、加密和其他安全原語建立在更受信任的內層之上。隨著軟體系統變得更加複雜，它們更有可能包含錯誤，這使它們容易受到安全威脅。因此，軟體系統變得越複雜，就越難以保護。信任根概念確保大部分信任放置在系統最不複雜的部分，因此是系統中最不易受攻擊的部分，而更複雜的軟體則圍繞其分層。這種安全架構以不同的規模重複，首先在單一系統的硬體內建立信任根，然後透過作業系統將該信任根擴展到更高級別的系統服務，最後跨越許多伺服器，以信任遞減的同心圓分層。

比特幣安全架構有所不同。在比特幣中，共識系統創建了一個完全去中心化的受信任區塊鏈。正確驗證的區塊鏈使用創世區塊作為信任根，建立一條信任鏈直到當前區塊。比特幣系統可以並且應該使用區塊鏈作為其信任根。在設計由許多不同系統上的服務組成的複雜比特幣應用程式時，您應該仔細檢查安全架構，以確定信任被放置在哪裡。最終，唯一應該被明確信任的是完全驗證的區塊鏈。如果您的應用程式明確或隱含地將信任賦予區塊鏈以外的任何事物，那應該是關注的來源，因為它引入了漏洞。評估應用程式安全架構的一個好方法是考慮每個單獨的組件，並評估該組件完全被破壞並在惡意行為者的控制下的假設情境。依次檢查應用程式的每個組件，並評估如果該組件被破壞，對整體安全性的影響。如果您的應用程式在組件被破壞時不再安全，這表明您在這些組件中錯誤地放置了信任。沒有漏洞的比特幣應用程式應該只容易受到比特幣共識機制的破壞，這意味著其信任根基於比特幣安全架構中最強大的部分。

被駭的比特幣交易所的眾多例子用來強調這一點，因為它們的安全架構和設計即使在最粗略的審查下也會失敗。這些集中式實作明確地將信任投資於比特幣區塊鏈之外的眾多組件，例如熱錢包、集中式資料庫、易受攻擊的加密金鑰和 ((("Bitcoin", "security", "principles of", startref="bitcoin-security-principle")))((("security", "principles of", startref="security-principle")))((("root of trust", startref="root-trust")))類似方案。

=== 用戶安全最佳實踐

人類 ((("Bitcoin", "security", "best practices", id="bitcoin-security-best-practice")))((("security", "best practices", id="security-best-practice")))((("best practices, security", id="best-practice-security")))使用物理安全控制已有數千年的歷史。相比之下，我們在數位安全方面的經驗不到 50 年。現代通用作業系統不是很安全，也不是特別適合儲存數位貨幣。我們的電腦透過持續開啟的網際網路連接不斷暴露於外部威脅。它們運行來自數百位作者的數千個軟體組件，通常對用戶的檔案有無限制的存取權。在您電腦上安裝的數千個軟體中的單一惡意軟體可以破壞您的鍵盤和檔案，竊取儲存在錢包應用程式中的任何比特幣。保持電腦無病毒和無木馬所需的電腦維護水平超出了絕大多數電腦用戶的技能水平。

儘管在資訊安全方面進行了數十年的研究和進步，數位資產仍然非常容易受到有決心的對手的攻擊。即使是金融服務公司、情報機構和國防承包商中最受保護和限制的系統，也經常被入侵。比特幣創建了具有內在價值的數位資產，可以被竊取並立即且不可逆轉地轉移給新所有者。這為駭客創造了巨大的動機。到目前為止，駭客必須在破壞身份資訊或帳戶憑證（例如信用卡和銀行帳戶）後將其轉換為價值。儘管圍欄和洗錢金融資訊困難重重，但我們看到盜竊事件不斷升級。比特幣使這個問題升級，因為它不需要被圍欄或洗錢；比特幣本身就是有價值的。

比特幣也創造了改善電腦安全的動機。以前，電腦破壞的風險是模糊和間接的，比特幣使這些風險變得清晰和明顯。在電腦上持有比特幣有助於將用戶的注意力集中在改善電腦安全的需求上。作為比特幣和其他數位貨幣激增和增加採用的直接結果，我們看到了駭客技術和安全解決方案的升級。簡單來說，駭客現在有一個非常誘人的目標，用戶有明確的動機來保護自己。

在過去三年中，作為比特幣採用的直接結果，我們在資訊安全領域看到了巨大的創新，以硬體加密、金鑰儲存和硬體簽章裝置、多重簽章技術和數位託管的形式出現。在以下各節中，我們將檢查實用用戶安全的各種最佳實踐。

==== 比特幣的物理儲存

因為大多數 ((("bitcoins", "physical storage")))((("physical bitcoin storage")))((("storing bitcoins", id="storing-bitcoin")))用戶對物理安全比資訊安全更熟悉，保護比特幣的一個非常有效的方法是將它們轉換為物理形式。比特幣金鑰以及用於創建它們的種子不過是長數字。這意味著它們可以以物理形式儲存，例如列印在紙上或蝕刻在金屬板上。保護金鑰然後變得像物理保護金鑰種子的列印副本一樣簡單。列印在紙上的種子稱為「紙本備份」，許多錢包可以創建它們。將比特幣保持離線 ((("cold storage")))稱為_冷儲存_，它是最有效的安全技術之一。冷儲存系統是指在離線系統（從未連接到網際網路的系統）上產生金鑰並將其儲存在紙上或數位媒體（例如 USB 記憶棒）上離線的系統。

==== 硬體簽章裝置

從長遠來看，比特幣 ((("hardware signing devices")))安全可能越來越多地採取防竄改硬體簽章裝置的形式。與智慧型手機或桌上型電腦不同，比特幣硬體簽章裝置只需要保存金鑰並使用它們來產生簽章。沒有通用軟體可以破壞，並且具有有限的介面，硬體簽章裝置可以為非專家用戶提供強大的安全性。硬體簽章裝置可能成為儲存比特幣的主要方法。

==== 確保您的存取

儘管大多數用戶 ((("backing up", "importance of")))理所當然地擔心他們的比特幣被盜，但還有一個更大的風險。資料檔案一直在丟失。如果它們包含比特幣金鑰，損失就會更加痛苦。在努力保護他們的比特幣錢包時，用戶必須非常小心，不要走得太遠，最終失去他們的比特幣。2011 年 7 月，一個著名的比特幣意識和教育專案損失了近 7,000 個比特幣。為了防止盜竊，所有者實施了一系列複雜的加密備份。最終，他們不小心遺失了加密金鑰，使備份變得毫無價值，並損失了一筆財富。就像透過將錢埋在沙漠中來隱藏錢一樣，如果您過度保護您的比特幣，您可能無法再次找到它們。

[WARNING]
====
要花費比特幣，您可能 ((("wallets", "recovery codes")))((("recovery codes")))需要備份的不僅僅是您的私鑰或用於衍生它們的 BIP32 種子。當使用多重簽章或複雜腳本時尤其如此。大多數輸出腳本承諾必須滿足的實際條件才能花費該輸出中的比特幣，除非您的錢包軟體可以向網路揭示這些條件，否則無法滿足該承諾。錢包恢復程式碼必須包含此資訊。有關更多詳細資訊，請參閱 <<ch05_wallets>>。
====

==== 分散風險

您會 ((("risk diversification")))((("storing bitcoins", startref="storing-bitcoin")))將您的全部淨資產以現金形式放在錢包中嗎？大多數人會認為這是魯莽的，但比特幣用戶經常使用單一錢包應用程式保管他們所有的比特幣。相反，用戶應該在多個不同的比特幣應用程式之間分散風險。謹慎的用戶將僅將一小部分（可能少於 5%）的比特幣保存在線上或行動錢包中作為「零用錢」。其餘部分應在幾種不同的儲存機制之間分配，例如桌面錢包和離線（冷儲存）。

==== 多重簽章與治理

每當 ((("multisignature addresses")))((("addresses", "multisignature")))公司或個人儲存大量比特幣時，他們應該考慮使用多重簽章比特幣地址。多重簽章地址透過要求多個簽章來進行付款來保護資金。簽章金鑰應儲存在許多不同的位置，並由不同的人控制。例如，在企業環境中，金鑰應由幾位公司高管獨立產生和持有，以確保沒有單一個人可以破壞資金。多重簽章地址也可以提供冗餘，其中單一個人持有儲存在不同位置的多個金鑰。


==== 生存能力

一個經常被忽視的重要安全 ((("survivability (of bitcoin access)")))((("estate planning")))考慮因素是可用性，特別是在金鑰持有者喪失能力或死亡的情況下。比特幣用戶被告知使用複雜的密碼並保持其金鑰的安全和私密，不與任何人分享。不幸的是，這種做法使得用戶的家人幾乎不可能在用戶無法解鎖時恢復任何資金。事實上，在大多數情況下，比特幣用戶的家人可能完全不知道比特幣資金的存在。

如果您有很多比特幣，您應該考慮與值得信賴的親戚或律師分享存取詳細資訊。可以透過多重簽章存取和透過專門擔任「數位資產執行人」的律師進行遺產規劃來設定更複雜的生存能力方案。

比特幣是一項複雜的新技術，開發人員仍在探索中。隨著時間的推移，我們將開發出更好的安全工具和實踐，非專家更容易使用。現在，比特幣用戶可以使用這裡討論的許多技巧來享受安全且無故障的比特幣 ((("Bitcoin", "security", "best practices", startref="bitcoin-security-best-practice")))((("security", "best practices", startref="security-best-practice")))((("best practices, security", startref="best-practice-security")))體驗。
