[preface]
== 快速詞彙表

//FIXME:include this?

這個快速詞彙表包含許多與比特幣相關的術語。這些術語在整本書中都有使用，因此請為此設定書籤以便快速參考。

address（地址）::
    比特幣地址看起來像 +1DSrfJdB2AnWaFNgSbv3MZC2m74996JafV+。它由一串字母和數字組成。它實際上是公鑰 160 位元雜湊的編碼 base58check 版本。就像你要求其他人將電子郵件傳送到你的電子郵件地址一樣，你會要求其他人將比特幣傳送到你的其中一個比特幣地址。

bip::
    比特幣改進提案（Bitcoin Improvement Proposals）。比特幣社群成員提交的一組旨在改進比特幣的提案。例如，BIP21 是一個改進比特幣統一資源識別碼（URI）方案的提案。

bitcoin（比特幣）::
    貨幣單位（幣）、網路和軟體的名稱。

block（區塊）::
    一組交易，用時間戳記標記，並對先前區塊的承諾。區塊頭被雜湊以產生工作量證明，從而驗證交易。有效區塊透過網路共識新增到主區塊鏈。

blockchain（區塊鏈）::
	經過驗證的區塊列表，每個區塊都連結到其前身，一直連結到創世區塊。

Byzantine Generals Problem（拜占庭將軍問題）::
    可靠的電腦系統必須能夠應對其一個或多個組件的故障。故障組件可能表現出一種經常被忽視的行為類型——即向系統的不同部分傳送衝突的資訊。處理這種故障的問題被抽象地表述為拜占庭將軍問題。

coinbase::
	用作 coinbase 交易的唯一輸入的特殊欄位。coinbase 允許索取區塊獎勵，並為任意資料提供最多 100 位元組。
	不要與 Coinbase 交易混淆。

coinbase transaction（Coinbase 交易）::
	區塊中的第一筆交易。始終由礦工建立，包含單一 coinbase。
	不要與 Coinbase 混淆。

cold storage（冷儲存）::
	指離線保留比特幣儲備。當比特幣私鑰在安全的離線環境中建立和儲存時，即實現冷儲存。對於擁有比特幣持有量的任何人來說，冷儲存都很重要。線上電腦容易受到駭客攻擊，不應用於儲存大量比特幣。

colored coins（彩色幣）::
	一個開源的 Bitcoin 2.0 協議，使開發者能夠在比特幣區塊鏈上建立數位資產，利用其超越貨幣的功能。

confirmations（確認）::
	一旦交易包含在區塊中，它就有一次確認。只要在同一區塊鏈上挖掘了 _另一個_ 區塊，交易就有兩次確認，依此類推。六次或更多確認被認為是交易無法逆轉的充分證明。

consensus（共識）::
    當多個節點（通常是網路上的大多數節點）在其本地驗證的最佳區塊鏈中都有相同的區塊時。
    不要與共識規則混淆。

consensus rules（共識規則）::
    完整節點遵循的區塊驗證規則，以與其他節點保持共識。
    不要與共識混淆。

difficulty（難度）::
	一個網路範圍的設定，控制產生工作量證明需要多少計算。

difficulty retargeting（難度重新定位）::
	每 2,016 個區塊進行一次的網路範圍難度重新計算，並考慮前 2,016 個區塊的雜湊算力。

difficulty target（難度目標）::
    網路中所有計算將以大約每 10 分鐘找到區塊的難度。

double-spending（雙重支付）::
    雙重支付是成功多次花費一些錢的結果。比特幣透過驗證新增到區塊鏈的每筆交易以確保交易的輸入之前沒有被花費過，從而防止雙重支付。

ECDSA::
    橢圓曲線數位簽章演算法（Elliptic Curve Digital Signature Algorithm）或 ECDSA 是比特幣使用的密碼學演算法，以確保資金只能由其合法所有者花費。

extra nonce（額外隨機數）::
    隨著難度增加，礦工經常循環遍歷 nonce 的所有 40 億個值而沒有找到區塊。因為 coinbase 腳本可以儲存 2 到 100 位元組的資料，礦工開始使用該空間作為額外的 nonce 空間，允許他們探索更大範圍的區塊頭值以找到有效區塊。

fees（手續費）::
	交易的傳送者通常向網路支付手續費以處理請求的交易。大多數交易需要至少 0.5 mBTC 的手續費。

fork（分叉）::
    分叉，也稱為意外分叉，發生在兩個或多個區塊具有相同的區塊高度時，使區塊鏈分叉。通常發生在兩個或多個礦工幾乎同時找到區塊時。也可能作為攻擊的一部分發生。

genesis block（創世區塊）::
	區塊鏈中的第一個區塊，用於初始化加密貨幣。

hard fork（硬分叉）::
    硬分叉，也稱為硬分叉變更，是區塊鏈中的永久分歧，通常發生在未升級的節點無法驗證由遵循較新共識規則的升級節點建立的區塊時。
    不要與分叉、軟分叉、軟體分叉或 Git 分叉混淆。

hardware wallet（硬體錢包）::
    硬體錢包是一種特殊類型的比特幣錢包，將使用者的私鑰儲存在安全的硬體裝置中。

//FIXME: needs improvement
hash（雜湊）::
    對某些二進位輸入的數位承諾。

hashlocks（雜湊鎖）::
    雜湊鎖是一種限制類型，限制輸出的花費，直到公開揭示指定的資料片段。雜湊鎖具有有用的屬性，即一旦公開開啟任何雜湊鎖，也可以開啟使用相同金鑰保護的任何其他雜湊鎖。這使得可以建立多個都受相同雜湊鎖限制並且都同時可花費的輸出。

HD protocol（HD 協議）::
    階層式確定性（Hierarchical Deterministic，HD）金鑰建立和傳輸協議（BIP32），允許從父金鑰的階層中建立子金鑰。

HD wallet（HD 錢包）::
    使用階層式確定性（HD 協議）金鑰建立和傳輸協議（BIP32）的錢包。

HD wallet seed（HD 錢包種子）::
    HD 錢包種子或根種子是一個潛在的短值，用作種子以生成 HD 錢包的主私鑰和主鏈碼。

HTLC::
    雜湊時間鎖定合約（Hashed TimeLock Contract）或 HTLC 是一類付款，使用雜湊鎖和時間鎖來要求付款接收者在截止日期前透過生成付款的密碼學證明來確認收到付款，或放棄索取付款的能力，將其退還給付款人。

KYC::
    了解你的客戶（Know your customer，KYC）是企業識別和驗證其客戶身分的過程。該術語也用於指規範這些活動的銀行法規。

LevelDB::
    LevelDB 是一個開源的磁碟鍵值儲存。LevelDB 是一個輕量級、單一用途的持久化函式庫，具有對許多平台的繫結。

Lightning Networks（閃電網路）::
    閃電網路是雜湊時間鎖定合約（HTLC）與雙向支付通道的建議實作，允許透過多個點對點支付通道安全地路由付款。這允許形成一個網路，其中網路上的任何對等點都可以向任何其他對等點付款，即使他們之間沒有直接開啟通道。

Lock time（鎖定時間）::
    鎖定時間是交易的一部分，表示該交易可以新增到區塊鏈的最早時間或最早區塊。

mempool（記憶體池）::
    比特幣記憶體池（memory pool）是區塊中所有已被比特幣節點驗證但尚未確認的交易資料的集合。

merkle root（默克爾根）::
    默克爾樹的根節點，是樹中所有雜湊對的後代。區塊頭必須包括從該區塊中所有交易派生的有效默克爾根。

merkle tree（默克爾樹）::
    透過雜湊配對的資料（葉子），然後配對和雜湊結果直到剩下一個雜湊（默克爾根）來構建的樹。在比特幣中，葉子幾乎總是來自單一區塊的交易。

miner（礦工）::
    一個網路節點，透過重複雜湊為新區塊找到有效的工作量證明。

multisignature（多重簽章）::
    多重簽章（multisig）是指需要多個金鑰來授權比特幣交易。

network（網路）::
    將交易和區塊傳播到網路上每個比特幣節點的點對點網路。

nonce（隨機數）::
    比特幣區塊中的「nonce」是一個 32 位元（4 位元組）欄位，其值被設定為使區塊的雜湊將包含一系列前導零。其餘欄位可能不會更改，因為它們具有定義的意義。

offchain transactions（鏈外交易）::
    鏈外交易是區塊鏈之外的價值移動。雖然鏈上交易&#x2014;通常簡稱為 __a transaction__&#x2014;修改區塊鏈並依賴區塊鏈來確定其有效性，但鏈外交易依賴其他方法來記錄和驗證交易。

opcode（操作碼）::
    來自比特幣腳本語言的操作碼，在 pubkey 腳本或簽章腳本中推送資料或執行函數。

OP_RETURN::
    在 OP_RETURN 交易的其中一個輸出中使用的操作碼。不要與 OP_RETURN 交易混淆。

OP_RETURN transaction（OP_RETURN 交易）::
    一種交易類型，將任意資料新增到可證明不可花費的 pubkey 腳本中，完整節點不必將其儲存在其 UTXO 資料庫中。不要與 OP_RETURN 操作碼混淆。

orphan block（孤兒區塊）::
    其父區塊尚未被本地節點處理的區塊，因此它們還無法完全驗證。不要與過時區塊混淆。

orphan transactions（孤兒交易）::
    由於缺少一個或多個輸入交易而無法進入池的交易。

output（輸出）::
    輸出、交易輸出或 TxOut 是交易中的輸出，包含兩個欄位：用於轉移零個或多個聰的值欄位和用於指示必須滿足哪些條件才能進一步花費這些聰的 pubkey 腳本。

P2PKH::
    支付給比特幣地址的交易包含 P2PKH 或 Pay To PubKey Hash 腳本。由 P2PKH 腳本鎖定的輸出可以透過提供公鑰和由相應私鑰建立的數位簽章來解鎖（花費）。

P2SH::
    P2SH 或 Pay-to-Script-Hash 是一種強大的新型交易，大大簡化了複雜交易腳本的使用。使用 P2SH，詳細說明花費輸出條件的複雜腳本（贖回腳本）不會出現在鎖定腳本中。相反，鎖定腳本中只有它的雜湊。

P2SH address（P2SH 地址）::
    P2SH 地址是腳本的 20 位元組雜湊的 Base58Check 編碼，P2SH 地址使用版本字首「5」，這導致以「3」開頭的 Base58Check 編碼地址。P2SH 地址隱藏了所有複雜性，因此付款的人看不到腳本。

P2WPKH::
    P2WPKH（Pay-to-Witness-Public-Key-Hash）的簽章包含與 P2PKH 花費相同的資訊，但位於見證結構中而不是輸入腳本中。輸出腳本也被修改。

P2WSH::
    P2SH 和 P2WSH（Pay-to-Witness-Script-Hash）之間的區別在於密碼學證明位置從輸入腳本更改為見證結構，輸出腳本也被修改。

paper wallet（紙錢包）::
    在最具體的意義上，紙錢包是包含生成任意數量比特幣私鑰所需的所有資料的文件，形成金鑰錢包。但是，人們經常使用該術語來表示將比特幣作為實體文件離線儲存的任何方式。第二個定義還包括紙金鑰和可贖回代碼。

payment channels（支付通道）::
    微支付通道或支付通道是一類技術，旨在允許使用者進行多次比特幣交易而不將所有交易提交到比特幣區塊鏈。在典型的支付通道中，只有兩筆交易新增到區塊鏈，但參與者之間可以進行無限或幾乎無限數量的付款。

pooled mining（礦池挖礦）::
    礦池挖礦是一種挖礦方法，其中多個生成客戶端為區塊的生成做出貢獻，然後根據貢獻的處理能力分配區塊獎勵。

Proof-of-Stake（權益證明）::
    權益證明（Proof-of-Stake，PoS）是加密貨幣區塊鏈網路旨在實現分散式共識的一種方法。權益證明要求使用者證明擁有一定數量的貨幣（他們在貨幣中的「權益」）。

Proof-of-Work（工作量證明）::
    需要大量計算才能找到的一段資料。在比特幣中，礦工必須找到 SHA256 演算法的數值解，該解滿足網路範圍的目標，即難度目標。

reward（獎勵）::
    作為網路對找到工作量證明解決方案的礦工的獎勵，每個新區塊中包含的金額。目前每個區塊為 12.5 BTC。

RIPEMD-160::
    RIPEMD-160 是一個 160 位元密碼學雜湊函數。RIPEMD-160 是 RIPEMD 的增強版本，具有 160 位元雜湊結果，預計在未來十年或更長時間內是安全的。

satoshi（聰）::
    聰是可以在區塊鏈上記錄的最小比特幣面額。它相當於 0.00000001 比特幣，以比特幣的創造者中本聰命名。

Satoshi Nakamoto（中本聰）::
    中本聰是設計比特幣並建立其原始參考實作 Bitcoin Core 的人使用的名字。作為實作的一部分，他們還設計了第一個區塊鏈資料庫。在此過程中，他們是第一個解決數位貨幣雙重支付問題的人。他們的真實身分仍然未知。

Script（腳本）::
    比特幣對交易使用腳本系統。類似 Forth，腳本簡單、基於堆疊，並從左到右處理。它故意不是圖靈完備的，沒有迴圈。

Output script（輸出腳本）::
    包含在輸出中的腳本，設定必須滿足的條件才能花費這些聰。滿足條件的資料可以在簽章腳本中提供。

Input script（輸入腳本）::
    由支出者生成的資料，幾乎總是用作變數來滿足輸出腳本。

secret key (aka private key)（私鑰）::
	解鎖傳送到相應地址的比特幣的秘密數字。pass:[<span class="keep-together">私鑰</span>]看起來像以下內容：
+
----
5J76sF8L5jTtzE96r66Sf8cka9y44wdpJjMwCxR3tzLh3ibVPxh
----

Segregated Witness（隔離見證）::
    隔離見證是比特幣協議的建議升級，其技術創新將簽章資料與比特幣交易分離。隔離見證是一個建議的軟分叉；一種技術上使比特幣協議規則更具限制性的變更。

SHA::
    安全雜湊演算法（Secure Hash Algorithm）或 SHA 是由美國國家標準與技術研究院（NIST）發佈的一系列密碼學雜湊函數。

Simplified Payment Verification (SPV)（簡化支付驗證）::
    一種驗證特定交易是否包含在區塊中而不下載整個區塊的方法。該方法由一些輕量級比特幣客戶端使用。

soft fork（軟分叉）::
    軟分叉或軟分叉變更是區塊鏈中的臨時分叉，通常發生在使用未升級節點的礦工不遵循他們的節點不知道的新共識規則時。
    不要與分叉、硬分叉、軟體分叉或 Git 分叉混淆。

stale block（過時區塊）::
    成功挖掘但未包含在當前最佳區塊鏈中的區塊，可能是因為同一高度的其他一些區塊首先擴展了其鏈。不要與孤兒區塊混淆。

timelocks（時間鎖）::
    時間鎖是一種限制類型，限制某些比特幣的花費，直到指定的未來時間或區塊高度。時間鎖在許多比特幣合約中發揮重要作用，包括支付通道和雜湊時間鎖定合約。

transaction（交易）::
    簡單來說，比特幣從一個地址到另一個地址的轉移。更準確地說，交易是表示價值轉移的簽署資料結構。交易透過比特幣網路傳輸，由礦工收集，並包含在區塊中，在區塊鏈上變得永久。

transaction pool（交易池）::
    不在主鏈區塊中但我們有輸入交易的交易的無序集合。

Turing completeness（圖靈完備性）::
    如果程式語言可以執行圖靈機可以執行的任何程式（給定足夠的時間和記憶體），則稱為「圖靈完備」。

unspent transaction output (UTXO)（未花費交易輸出）::
    UTXO 是可以在新交易中作為輸入花費的未花費交易輸出。

wallet（錢包）::
    儲存你所有比特幣地址和私鑰的軟體。使用它來傳送、接收和儲存你的比特幣。

Wallet Import Format (WIF)（錢包匯入格式）::
    WIF 或錢包匯入格式是一種資料交換格式，旨在允許匯出和匯入單一私鑰以及指示它是否使用壓縮公鑰的標誌。

一些貢獻的定義已根據 CC-BY 授權從 https://en.bitcoin.it/wiki/Main_Page[bitcoin Wiki] 或其他開源文件來源獲得。
