name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'zh-tw/**'
      - 'images/**'
      - '.github/workflows/build-and-deploy.yml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Install AsciiDoctor and dependencies
        run: |
          gem install asciidoctor
          gem install rouge

      - name: Create output directory
        run: mkdir -p public

      - name: Build HTML
        run: |
          cd zh-tw
          asciidoctor \
            --backend=html5 \
            --out-file=../public/index.html \
            --attribute=source-highlighter=rouge \
            --attribute=toc=left \
            --attribute=toclevels=2 \
            --attribute=icons=font \
            --attribute=sectanchors \
            --attribute=idprefix= \
            --attribute=idseparator=- \
            --attribute=docinfo=shared \
            book.adoc

      - name: Copy images to output
        run: |
          cp -r images public/images

      - name: Copy SEO files
        run: |
          cp zh-tw/robots.txt public/robots.txt
          cp zh-tw/sitemap.xml public/sitemap.xml

      - name: Create CNAME file for custom domain
        run: |
          echo "bitcoinbook-3nd-zh.doge.tg" > public/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
